# GREEN GRID INDIA - Verified Renewable Energy Supplier Database
# Research snapshot: October 2026 | India-focused | Technical & Procurement Ready

ENERGY_PROVIDERS = [
    {
        "name": "Adani Green Energy (AGEL)",
        "category": "ipp",
        "capacity_mw": 20000.0,
        "available_capacity_mw": 4500.0,
        "energy_types": ["Solar", "Wind", "Hybrid", "BESS"],
        "sourcing_models": ["Physical PPA", "vPPA", "Open Access", "RTC/FDRE"],
        "states_covered": ["Gujarat", "Rajasthan", "Maharashtra", "Pan-India"],
        "min_contract_years": 10,
        "price_per_unit_inr": {"min": 3.75, "max": 4.85},
        "rtc_availability_pct": 88,
        "website": "https://www.adanigreenenergy.com",
        "latitude": 23.8500,
        "longitude": 69.7500,
        "is_verified": True,
        "description": "20+ GW operational (Jul 2026); >52 billion units annual clean generation; flagship Khavda Mega RE Park targeting 30 GW. FY26 energy sales 37,567 MU; FY26 power revenue ₹11,602 crore."
    },
    {
        "name": "ReNew (ReNew Power)",
        "category": "ipp",
        "capacity_mw": 12600.0,
        "available_capacity_mw": 2600.0,
        "energy_types": ["Solar", "Wind", "BESS"],
        "sourcing_models": ["Physical PPA", "vPPA", "RTC/FDRE"],
        "states_covered": ["Rajasthan", "Karnataka", "Andhra Pradesh", "Maharashtra"],
        "min_contract_years": 8,
        "price_per_unit_inr": {"min": 4.15, "max": 5.05},
        "rtc_availability_pct": 84,
        "website": "https://www.renew.com",
        "latitude": 28.4595,
        "longitude": 77.0266,
        "is_verified": True,
        "description": "~12.6 GW operating; ~20 GW gross portfolio. In FY26 commissioned ~2.4 GW (1.75 GW solar + 0.62 GW wind + 25 MW/100 MWh BESS). Custom wind-solar-storage RTC hybrid."
    },
    {
        "name": "Tata Power Renewable Energy (TPREL)",
        "category": "ipp",
        "capacity_mw": 11600.0,
        "available_capacity_mw": 2100.0,
        "energy_types": ["Solar", "Wind", "Hybrid/FDRE", "BESS"],
        "sourcing_models": ["Physical PPA", "Open Access", "RTC/FDRE"],
        "states_covered": ["Maharashtra", "Tamil Nadu", "Rajasthan", "Gujarat", "Karnataka"],
        "min_contract_years": 10,
        "price_per_unit_inr": {"min": 4.10, "max": 5.20},
        "rtc_availability_pct": 82,
        "website": "https://www.tatapowerrenewables.com",
        "latitude": 18.9220,
        "longitude": 72.8347,
        "is_verified": True,
        "description": "11.6 GW total utility renewable capacity including 9.4 GW contracted PPA; 6.3 GW operational (5.1 GW solar + 1.2 GW wind). Manufacturing facility in Tirunelveli."
    },
    {
        "name": "Avaada Energy",
        "category": "ipp",
        "capacity_mw": 7300.0,
        "available_capacity_mw": 1500.0,
        "energy_types": ["Solar", "Wind", "Hybrid", "FDRE", "BESS"],
        "sourcing_models": ["Physical PPA", "Open Access", "RTC/FDRE"],
        "states_covered": ["Rajasthan", "Maharashtra", "Gujarat", "Karnataka"],
        "min_contract_years": 12,
        "price_per_unit_inr": {"min": 3.95, "max": 4.90},
        "rtc_availability_pct": 76,
        "website": "https://www.avaada.com",
        "latitude": 28.0176,
        "longitude": 73.3119,
        "is_verified": True,
        "description": "~7.2–7.3 GWp operational; >17.7 GWp portfolio including construction. Flagship Bikaner 1.25 GWp single-site solar park; integrated AI-ready DC clean power provider."
    },
    {
        "name": "JSW Energy (JSW Neo Energy)",
        "category": "ipp",
        "capacity_mw": 9190.0,
        "available_capacity_mw": 1400.0,
        "energy_types": ["Wind", "Solar", "Hybrid", "Hydro", "BESS", "Pumped Hydro"],
        "sourcing_models": ["Physical PPA", "Open Access", "RTC/FDRE"],
        "states_covered": ["Karnataka", "Maharashtra", "Tamil Nadu", "Pan-India"],
        "min_contract_years": 10,
        "price_per_unit_inr": {"min": 3.65, "max": 4.85},
        "rtc_availability_pct": 80,
        "website": "https://www.jsw.in/energy",
        "latitude": 15.1394,
        "longitude": 76.9214,
        "is_verified": True,
        "description": "~9.19 GW renewable operational (reported Oct 2026); 15.15 GW total platform; 29.6 GWh storage locked in. Long-term target of 30 GW generation + 40 GWh storage by 2030."
    },
    {
        "name": "Greenko Group",
        "category": "ipp",
        "capacity_mw": 7500.0,
        "available_capacity_mw": 1800.0,
        "energy_types": ["Pumped Hydro", "Solar", "Wind"],
        "sourcing_models": ["Physical PPA", "Open Access", "RTC/FDRE"],
        "states_covered": ["Andhra Pradesh", "Telangana", "Karnataka"],
        "min_contract_years": 15,
        "price_per_unit_inr": {"min": 4.35, "max": 5.35},
        "rtc_availability_pct": 92,
        "website": "https://www.greenkogroup.com",
        "latitude": 15.6820,
        "longitude": 78.2710,
        "is_verified": True,
        "description": "Integrated renewable + pumped hydro storage platform. Pinnapuram IREP (1,200 MW pumped hydro + 2,000 MW solar + 400 MW wind) delivering 24/7 firm baseload renewable power."
    },
    {
        "name": "NTPC Green Energy (NGEL)",
        "category": "ipp",
        "capacity_mw": 10000.0,
        "available_capacity_mw": 2500.0,
        "energy_types": ["Solar", "Wind", "Hybrid", "Storage"],
        "sourcing_models": ["Physical PPA", "Green Tariff", "RTC/FDRE"],
        "states_covered": ["Gujarat", "Rajasthan", "Andhra Pradesh", "Pan-India"],
        "min_contract_years": 15,
        "price_per_unit_inr": {"min": 3.85, "max": 4.80},
        "rtc_availability_pct": 82,
        "website": "https://www.ntpc.co.in",
        "latitude": 28.5355,
        "longitude": 77.3910,
        "is_verified": True,
        "description": "PSU clean energy flagship targeting 60 GW by 2032 with mega solar and wind complexes across Gujarat and Rajasthan. Strong utility-scale and RTC/FDRE pipeline."
    },
    {
        "name": "ACME Solar",
        "category": "ipp",
        "capacity_mw": 2800.0,
        "available_capacity_mw": 600.0,
        "energy_types": ["Solar", "Wind", "Hybrid", "FDRE"],
        "sourcing_models": ["Physical PPA", "Open Access", "RTC/FDRE"],
        "states_covered": ["Rajasthan", "Gujarat", "Pan-India"],
        "min_contract_years": 10,
        "price_per_unit_inr": {"min": 3.80, "max": 4.75},
        "rtc_availability_pct": 78,
        "website": "https://www.acme.in",
        "latitude": 27.5397,
        "longitude": 71.9161,
        "is_verified": True,
        "description": "~2.8 GW solar operational; expanding hybrid/FDRE pipeline with recent Bikaner hybrid commissioning linked to long-term NTPC PPA."
    },
    {
        "name": "Sembcorp Green Infra",
        "category": "ipp",
        "capacity_mw": 4200.0,
        "available_capacity_mw": 800.0,
        "energy_types": ["Solar", "Wind", "Hybrid", "Storage"],
        "sourcing_models": ["Physical PPA", "Open Access"],
        "states_covered": ["Gujarat", "Karnataka", "Madhya Pradesh", "Tamil Nadu"],
        "min_contract_years": 10,
        "price_per_unit_inr": {"min": 4.05, "max": 4.95},
        "rtc_availability_pct": 79,
        "website": "https://www.sembcorp.com",
        "latitude": 21.1702,
        "longitude": 72.8311,
        "is_verified": True,
        "description": "Major utility-scale and C&I renewable platform providing tailored hybrid generation and storage contracts across India."
    },
    {
        "name": "Serentica Renewables",
        "category": "ipp",
        "capacity_mw": 4000.0,
        "available_capacity_mw": 900.0,
        "energy_types": ["Wind", "Solar", "Storage", "Firm Renewable"],
        "sourcing_models": ["Physical PPA", "RTC/FDRE", "Open Access"],
        "states_covered": ["Rajasthan", "Karnataka", "Maharashtra", "Pan-India"],
        "min_contract_years": 12,
        "price_per_unit_inr": {"min": 4.20, "max": 5.10},
        "rtc_availability_pct": 85,
        "website": "https://www.serenticaglobal.com",
        "latitude": 17.3850,
        "longitude": 78.4867,
        "is_verified": True,
        "description": "Firm renewable energy specialist dedicated to commercial and industrial decarbonisation; offers structured RTC and FDRE PPAs for data centers."
    },
    {
        "name": "CleanMax",
        "category": "ci",
        "capacity_mw": 2000.0,
        "available_capacity_mw": 450.0,
        "energy_types": ["Solar", "Wind", "Hybrid"],
        "sourcing_models": ["Open Access", "Group Captive", "Physical PPA"],
        "states_covered": ["Maharashtra", "Karnataka", "Tamil Nadu", "Gujarat"],
        "min_contract_years": 5,
        "price_per_unit_inr": {"min": 3.20, "max": 4.50},
        "rtc_availability_pct": 70,
        "website": "https://www.cleanmax.com",
        "latitude": 19.0178,
        "longitude": 72.8478,
        "is_verified": True,
        "description": "Corporate C&I sourcing specialist. Typical C&I benchmark ₹3.20–₹4.50/kWh. Powers Equinix Mumbai with 33 MW hybrid PPA and Web Werks with 32M kWh group captive arrays."
    },
    {
        "name": "Sunsure Energy",
        "category": "ci",
        "capacity_mw": 1500.0,
        "available_capacity_mw": 350.0,
        "energy_types": ["Solar", "Wind", "Hybrid"],
        "sourcing_models": ["Open Access", "Group Captive", "C&I"],
        "states_covered": ["Karnataka", "Uttar Pradesh", "Haryana", "Maharashtra", "Tamil Nadu"],
        "min_contract_years": 5,
        "price_per_unit_inr": {"min": 3.40, "max": 4.60},
        "rtc_availability_pct": 68,
        "website": "https://www.sunsure-energy.com",
        "latitude": 12.9716,
        "longitude": 77.5946,
        "is_verified": True,
        "description": "Bengaluru HQ C&I renewable developer backed by Partners Group. Delivers tailored corporate open-access solar, wind, and hybrid PPAs."
    },
    {
        "name": "Fourth Partner Energy",
        "category": "ci",
        "capacity_mw": 1400.0,
        "available_capacity_mw": 280.0,
        "energy_types": ["Solar", "Hybrid", "BESS", "C&I"],
        "sourcing_models": ["Open Access", "Group Captive"],
        "states_covered": ["Telangana", "Andhra Pradesh", "Maharashtra", "Tamil Nadu", "Karnataka"],
        "min_contract_years": 7,
        "price_per_unit_inr": {"min": 3.50, "max": 4.65},
        "rtc_availability_pct": 67,
        "website": "https://www.fourthpartner.co",
        "latitude": 17.4483,
        "longitude": 78.3915,
        "is_verified": True,
        "description": "Hyderabad HQ C&I renewable platform backed by British International Investment. Builds onsite solar, wind-solar hybrids, and offsite open-access."
    },
    {
        "name": "Hero Future Energies",
        "category": "ci",
        "capacity_mw": 1600.0,
        "available_capacity_mw": 300.0,
        "energy_types": ["Wind", "Solar", "Hybrid", "BESS"],
        "sourcing_models": ["Physical PPA", "Open Access"],
        "states_covered": ["Rajasthan", "Gujarat", "Andhra Pradesh", "Karnataka"],
        "min_contract_years": 8,
        "price_per_unit_inr": {"min": 3.60, "max": 4.70},
        "rtc_availability_pct": 66,
        "website": "https://www.herofutureenergies.com",
        "latitude": 28.5355,
        "longitude": 77.2610,
        "is_verified": True,
        "description": "Large independent renewable platform backed by KKR. Provides peak-time load-following power solutions and corporate PPAs."
    },
    {
        "name": "Suzlon Group",
        "category": "epc",
        "capacity_mw": 20000.0,
        "available_capacity_mw": 0.0,
        "energy_types": ["Wind", "Hybrid"],
        "sourcing_models": ["Behind-the-Meter", "Physical PPA"],
        "states_covered": ["Tamil Nadu", "Gujarat", "Maharashtra", "Rajasthan"],
        "min_contract_years": 5,
        "price_per_unit_inr": {"min": 3.50, "max": 4.50},
        "rtc_availability_pct": 75,
        "website": "https://www.suzlon.com",
        "latitude": 8.2612,
        "longitude": 77.5458,
        "is_verified": True,
        "description": "India's pioneer wind EPC developer with landmark installations across Muppandal (Tamil Nadu) executing high-CUF turbine integration for energy-intensive campuses."
    },
    {
        "name": "Sterling and Wilson Renewable Energy",
        "category": "epc",
        "capacity_mw": 15000.0,
        "available_capacity_mw": 0.0,
        "energy_types": ["Solar", "BESS"],
        "sourcing_models": ["Behind-the-Meter", "Physical PPA"],
        "states_covered": ["Andhra Pradesh", "Pan-India"],
        "min_contract_years": 3,
        "price_per_unit_inr": {"min": 3.40, "max": 4.40},
        "rtc_availability_pct": 72,
        "website": "https://www.sterlingandwilsonre.com",
        "latitude": 15.6820,
        "longitude": 78.2710,
        "is_verified": True,
        "description": "Global pure-play green EPC contractor for ultra-mega solar parks (e.g. Kurnool, AP) and utility-scale BESS battery installations."
    },
    {
        "name": "NHPC Renewable Energy",
        "category": "ipp",
        "capacity_mw": 7071.0,
        "available_capacity_mw": 1200.0,
        "energy_types": ["Small Hydro", "Hydro", "Pumped Hydro", "Solar"],
        "sourcing_models": ["Physical PPA", "RTC/FDRE", "Open Access"],
        "states_covered": ["Himachal Pradesh", "Uttarakhand", "Pan-India"],
        "min_contract_years": 15,
        "price_per_unit_inr": {"min": 3.80, "max": 4.60},
        "rtc_availability_pct": 89,
        "website": "https://www.nhpcindia.com",
        "latitude": 31.1048,
        "longitude": 77.1734,
        "is_verified": True,
        "description": "India's premier hydropower PSU providing 24/7 continuous run-of-the-river clean baseload and pumped storage to offset solar intermittency."
    },
    {
        "name": "Orient Green Power Company",
        "category": "ipp",
        "capacity_mw": 1100.0,
        "available_capacity_mw": 220.0,
        "energy_types": ["Biomass", "Wind", "Hybrid"],
        "sourcing_models": ["Open Access", "Physical PPA", "Group Captive"],
        "states_covered": ["Tamil Nadu", "Maharashtra", "Punjab", "Karnataka"],
        "min_contract_years": 8,
        "price_per_unit_inr": {"min": 4.20, "max": 5.20},
        "rtc_availability_pct": 85,
        "website": "https://www.orientgreenpower.com",
        "latitude": 13.0827,
        "longitude": 80.2707,
        "is_verified": True,
        "description": "Pioneer in non-intermittent biomass cogeneration and wind arrays across southern and western industrial grid corridors."
    }
]
