ENERGY_PROVIDERS = [
    {
        "name": "Adani Green Energy (AGEL)",
        "category": "ipp",
        "capacity_mw": 19500.0,
        "available_capacity_mw": 3200.0,
        "energy_types": ["Solar", "Wind", "Hybrid"],
        "sourcing_models": ["Physical PPA", "vPPA", "Open Access", "RTC/FDRE"],
        "states_covered": ["Gujarat", "Rajasthan", "Maharashtra", "Andhra Pradesh"],
        "min_contract_years": 10,
        "price_per_unit_inr": {"min": 3.8, "max": 4.9},
        "rtc_availability_pct": 85,
        "website": "https://www.adanigreenenergy.com",
        "latitude": 23.2156,
        "longitude": 72.6369,
        "is_verified": True,
        "description": "India's largest renewable portfolio with massive solar-wind parks like Khavda delivering round-the-clock power to tech giants."
    },
    {
        "name": "Tata Power Renewable Energy (TPREL)",
        "category": "ipp",
        "capacity_mw": 11600.0,
        "available_capacity_mw": 2100.0,
        "energy_types": ["Solar", "Wind", "Hybrid"],
        "sourcing_models": ["Physical PPA", "Open Access", "RTC/FDRE"],
        "states_covered": ["Maharashtra", "Tamil Nadu", "Rajasthan", "Gujarat"],
        "min_contract_years": 10,
        "price_per_unit_inr": {"min": 4.1, "max": 5.2},
        "rtc_availability_pct": 80,
        "website": "https://www.tatapowerrenewables.com",
        "latitude": 18.9220,
        "longitude": 72.8347,
        "is_verified": True,
        "description": "Pioneering Firm and Dispatchable Renewable Energy (FDRE) hybrid projects in Rajasthan and Tamil Nadu."
    },
    {
        "name": "ReNew (ReNew Power)",
        "category": "ipp",
        "capacity_mw": 13400.0,
        "available_capacity_mw": 2400.0,
        "energy_types": ["Wind", "Solar", "BESS"],
        "sourcing_models": ["Physical PPA", "vPPA", "RTC/FDRE"],
        "states_covered": ["Rajasthan", "Karnataka", "Andhra Pradesh", "Maharashtra"],
        "min_contract_years": 8,
        "price_per_unit_inr": {"min": 4.2, "max": 5.1},
        "rtc_availability_pct": 82,
        "website": "https://www.renew.com",
        "latitude": 28.4595,
        "longitude": 77.0266,
        "is_verified": True,
        "description": "Specialises in customized wind-solar-battery networks balancing evening energy drops for mission-critical facilities."
    },
    {
        "name": "Avaada Energy",
        "category": "ipp",
        "capacity_mw": 7200.0,
        "available_capacity_mw": 1500.0,
        "energy_types": ["Solar", "BESS", "Hybrid"],
        "sourcing_models": ["Physical PPA", "Open Access", "RTC/FDRE"],
        "states_covered": ["Maharashtra", "Rajasthan", "Gujarat", "Karnataka"],
        "min_contract_years": 12,
        "price_per_unit_inr": {"min": 4.0, "max": 4.9},
        "rtc_availability_pct": 76,
        "website": "https://www.avaada.com",
        "latitude": 19.0760,
        "longitude": 72.8777,
        "is_verified": True,
        "description": "Direct integrated model pairing utility scale generation with BESS for 76% time-matched green power directly at operational launch."
    },
    {
        "name": "Greenko Group",
        "category": "ipp",
        "capacity_mw": 7500.0,
        "available_capacity_mw": 1800.0,
        "energy_types": ["Pumped Hydro", "Solar", "Wind"],
        "sourcing_models": ["Physical PPA", "Open Access", "RTC/FDRE"],
        "states_covered": ["Andhra Pradesh", "Telangana", "Karnataka"],
        "min_contract_years": 15,
        "price_per_unit_inr": {"min": 4.4, "max": 5.4},
        "rtc_availability_pct": 90,
        "website": "https://www.greenkogroup.com",
        "latitude": 17.3850,
        "longitude": 78.4867,
        "is_verified": True,
        "description": "Pioneering massive Pumped Hydro Storage Projects (such as Pinnapuram) discharging 24/7 reliable round-the-clock power."
    },
    {
        "name": "JSW Neo Energy",
        "category": "ipp",
        "capacity_mw": 7600.0,
        "available_capacity_mw": 1200.0,
        "energy_types": ["Wind", "Solar", "Hydro"],
        "sourcing_models": ["Physical PPA", "Open Access"],
        "states_covered": ["Karnataka", "Maharashtra", "Tamil Nadu"],
        "min_contract_years": 10,
        "price_per_unit_inr": {"min": 4.1, "max": 5.0},
        "rtc_availability_pct": 78,
        "website": "https://www.jsw.in/energy",
        "latitude": 18.9894,
        "longitude": 72.8277,
        "is_verified": True,
        "description": "Rapidly scaling locked-in portfolio on roadmap to 30 GW by 2030, specializing in wind and hybrid power."
    },
    {
        "name": "NTPC Green Energy (NGEL)",
        "category": "ipp",
        "capacity_mw": 10000.0,
        "available_capacity_mw": 2500.0,
        "energy_types": ["Solar", "Wind", "Green Hydrogen"],
        "sourcing_models": ["Physical PPA", "Green Tariff", "RTC/FDRE"],
        "states_covered": ["Pan-India", "Rajasthan", "Gujarat", "Andhra Pradesh"],
        "min_contract_years": 15,
        "price_per_unit_inr": {"min": 3.9, "max": 4.8},
        "rtc_availability_pct": 80,
        "website": "https://www.ntpc.co.in",
        "latitude": 28.5355,
        "longitude": 77.3910,
        "is_verified": True,
        "description": "India's leading public-sector green utility commanding vast national generation infrastructure."
    },
    {
        "name": "CleanMax",
        "category": "ci",
        "capacity_mw": 2000.0,
        "available_capacity_mw": 450.0,
        "energy_types": ["Solar", "Wind", "Hybrid"],
        "sourcing_models": ["Open Access", "Physical PPA", "Group Captive"],
        "states_covered": ["Maharashtra", "Karnataka", "Tamil Nadu", "Telangana"],
        "min_contract_years": 5,
        "price_per_unit_inr": {"min": 4.5, "max": 5.5},
        "rtc_availability_pct": 70,
        "website": "https://www.cleanmax.com",
        "latitude": 19.0178,
        "longitude": 72.8478,
        "is_verified": True,
        "description": "Leader in C&I renewable procurement, structures dedicated captive arrays (e.g. 33 MW corporate solar-wind hybrid for Equinix Mumbai)."
    },
    {
        "name": "Sunsure Energy",
        "category": "ci",
        "capacity_mw": 1500.0,
        "available_capacity_mw": 350.0,
        "energy_types": ["Solar", "Wind"],
        "sourcing_models": ["Open Access", "Group Captive"],
        "states_covered": ["Haryana", "Uttar Pradesh", "Maharashtra", "Tamil Nadu"],
        "min_contract_years": 5,
        "price_per_unit_inr": {"min": 4.6, "max": 5.6},
        "rtc_availability_pct": 68,
        "website": "https://www.sunsure-energy.com",
        "latitude": 28.4908,
        "longitude": 77.0878,
        "is_verified": True,
        "description": "Industrial decarbonisation specialist backed by Partners Group, enabling corporations to substitute up to 100% of grid power."
    },
    {
        "name": "Hero Future Energies",
        "category": "ci",
        "capacity_mw": 1600.0,
        "available_capacity_mw": 300.0,
        "energy_types": ["Solar", "Wind", "BESS"],
        "sourcing_models": ["Physical PPA", "Open Access"],
        "states_covered": ["Rajasthan", "Gujarat", "Andhra Pradesh", "Karnataka"],
        "min_contract_years": 8,
        "price_per_unit_inr": {"min": 4.4, "max": 5.3},
        "rtc_availability_pct": 65,
        "website": "https://www.herofutureenergies.com",
        "latitude": 28.5355,
        "longitude": 77.2610,
        "is_verified": True,
        "description": "Backed by KKR, specializing in peak-time power supply and load-following corporate energy solutions."
    },
    {
        "name": "Fourth Partner Energy",
        "category": "ci",
        "capacity_mw": 1400.0,
        "available_capacity_mw": 280.0,
        "energy_types": ["Solar", "Wind", "BESS"],
        "sourcing_models": ["Open Access", "Group Captive"],
        "states_covered": ["Maharashtra", "Tamil Nadu", "Telangana", "Karnataka"],
        "min_contract_years": 7,
        "price_per_unit_inr": {"min": 4.5, "max": 5.4},
        "rtc_availability_pct": 67,
        "website": "https://www.fourthpartner.co",
        "latitude": 17.4483,
        "longitude": 78.3915,
        "is_verified": True,
        "description": "Backed by British International Investment, develops onsite solar, wind-solar hybrids, and offsite open-access."
    },
    {
        "name": "Sterling and Wilson Renewable Energy",
        "category": "epc",
        "capacity_mw": 15000.0,
        "available_capacity_mw": 0.0,
        "energy_types": ["Solar", "BESS"],
        "sourcing_models": ["Behind-the-Meter", "Physical PPA"],
        "states_covered": ["Pan-India"],
        "min_contract_years": 3,
        "price_per_unit_inr": {"min": 3.7, "max": 4.8},
        "rtc_availability_pct": 72,
        "website": "https://www.sterlingandwilsonre.com",
        "latitude": 18.9950,
        "longitude": 72.8250,
        "is_verified": True,
        "description": "Leading global pure-play green EPC contractor specializing in utility-scale installations, floating solar, and high-capacity BESS."
    },
    {
        "name": "Suzlon Group",
        "category": "epc",
        "capacity_mw": 20000.0,
        "available_capacity_mw": 0.0,
        "energy_types": ["Wind", "Hybrid"],
        "sourcing_models": ["Behind-the-Meter", "Physical PPA"],
        "states_covered": ["Gujarat", "Tamil Nadu", "Maharashtra", "Rajasthan"],
        "min_contract_years": 5,
        "price_per_unit_inr": {"min": 3.9, "max": 4.9},
        "rtc_availability_pct": 75,
        "website": "https://www.suzlon.com",
        "latitude": 18.5204,
        "longitude": 73.8567,
        "is_verified": True,
        "description": "India's dominant wind energy solutions pioneer, executes end-to-end full-stack renewable integration for heavy consumers."
    }
]
