# Generated by Django 6.1.2 on 2026-10-07 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ipp', 'Utility Hyperscale IPP'), ('ci', 'Commercial & Industrial (C&I) Specialist'), ('epc', 'EPC & Component Contractor')], default='ipp', max_length=10)),
                ('capacity_mw', models.FloatField(default=1000.0)),
                ('available_capacity_mw', models.FloatField(default=300.0)),
                ('energy_types', models.JSONField(default=list)),
                ('sourcing_models', models.JSONField(default=list)),
                ('states_covered', models.JSONField(default=list)),
                ('min_contract_years', models.IntegerField(default=10)),
                ('price_per_unit_inr', models.JSONField(default=dict)),
                ('rtc_availability_pct', models.IntegerField(default=80)),
                ('website', models.URLField(blank=True)),
                ('latitude', models.FloatField(default=19.076)),
                ('longitude', models.FloatField(default=72.8777)),
                ('is_verified', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
