# Generated by Django 6.1.2 on 2026-10-07 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcbuilder', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0)),
                ('ai_analysis', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Match'), ('accepted', 'Accepted / Inquired'), ('rejected', 'Declined'), ('negotiating', 'In Active Negotiation')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='dcbuilder.dcprofile')),
                ('supplier_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='supplier.supplierprofile')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('dc_profile', 'supplier_profile')},
            },
        ),
    ]
