# Generated by Django 6.1.2 on 2026-10-07 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='New Green DC Project', max_length=200)),
                ('preferred_city', models.CharField(default='Mumbai', max_length=100)),
                ('preferred_state', models.CharField(default='Maharashtra', max_length=100)),
                ('latitude', models.FloatField(blank=True, default=19.076, null=True)),
                ('longitude', models.FloatField(blank=True, default=72.8777, null=True)),
                ('tier', models.CharField(choices=[('tier3', 'Tier III'), ('tier4', 'Tier IV')], default='tier3', max_length=10)),
                ('it_load_mw', models.FloatField(default=10.0)),
                ('server_types', models.JSONField(default=list)),
                ('cooling_type', models.CharField(choices=[('liquid', 'Liquid Cooling (Direct-to-Chip / Immersion)'), ('air', 'Precision Air Cooling (CRAH/CRAC)'), ('hybrid', 'Hybrid Evaporative / Liquid')], default='liquid', max_length=20)),
                ('target_pue', models.FloatField(default=1.35)),
                ('green_goal_pct', models.IntegerField(default=100)),
                ('sourcing_models', models.JSONField(default=list)),
                ('budget_inr_cr', models.JSONField(default=dict)),
                ('launch_timeline', models.CharField(default='Q4 2026', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dc_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DCAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_annual_mwh', models.FloatField()),
                ('peak_demand_mw', models.FloatField()),
                ('renewable_needed_mw', models.FloatField()),
                ('cooling_overhead_pct', models.FloatField(default=25.0)),
                ('recommended_sourcing_models', models.JSONField(default=list)),
                ('preferred_energy_types', models.JSONField(default=list)),
                ('location_scores', models.JSONField(default=dict)),
                ('reasoning', models.TextField(blank=True)),
                ('raw_ai_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dc_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='dcbuilder.dcprofile')),
            ],
        ),
    ]
